server:
  port: 8081

spring:
  application:
    name: order-service

kafka:
  bootstrap-servers: localhost:9092
  topics:
    order:
      create: order.create
      cancel: order.cancel

  # Enable H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console

  # Datasource Configuration (Used embedded H2 database)
  datasource:
    generate-unique-name: false

  # JPA Configuration
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    producer:
      bootstrap-servers: ${kafka.bootstrap-servers}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: ${kafka.bootstrap-servers}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest